### Importing numpy package as np for processing numberics as numpy array

In [3]:
import numpy as np

### Creating static 2 numpy array in variable a and b of size 3*3 using array() function 

In [4]:
a = np.array([[1, 2, 3], [4, 5, 6], [7 ,8 , 9]])
b = np.array([[3, 2, 1], [6, 5, 4], [9, 8, 7]])

#### Printing Values of a and b

In [5]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Adding two numpy arrays a and b to create c

In [6]:
c = a+b

In [7]:
c

array([[ 4,  4,  4],
       [10, 10, 10],
       [16, 16, 16]])

### Creating a new numpy array and assigning to varibale d and two scalars e and f and performing multiplication

In [8]:
d = np.array([[1,2,3], [7,8,9], [10,11,12], [5,7,9]])
e = 1
f = 2

In [9]:
d*e

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [10, 11, 12],
       [ 5,  7,  9]])

In [10]:
d*f

array([[ 2,  4,  6],
       [14, 16, 18],
       [20, 22, 24],
       [10, 14, 18]])

### Using random module using randint() function to create a numpy array of dim 5\*1

In [11]:
g = np.random.randint(1, 199, size=(5,1))

In [12]:
g

array([[ 65],
       [163],
       [ 22],
       [153],
       [182]])

#### Dimensions of the created array using shape() and ndim function

In [13]:
g.shape

(5, 1)

In [16]:
g.ndim

2

### Using reshape() function to change the dimensions of matrix from 5\*1 to 1\*5

In [27]:
h = np.reshape(g, (1,5))

In [28]:
h

array([[151, 114,  76, 188, 186]])

### Using transpose() function to change the matrix from 1\*5 to 5\*1 back

In [30]:
np.transpose(h)

array([[151],
       [114],
       [ 76],
       [188],
       [186]])

### What is matrics ?

A matrix is a grid of n × m (say, 3 × 3) numbers surrounded by brackets. We can add and subtract matrices of the same size, multiply one matrix with another as long as the sizes are compatible ((n × m) × (m × p) = n × p), and multiply an entire matrix by a constant. A vector is a matrix with just one row or column. So there are a bunch of mathematical operations that we can do to any matrix.

### What is a tensor ?

A tensor is often thought of as a generalized matrix. That is, it could be a 1-D matrix (a vector is actually such a tensor), a 3-D matrix (something like a cube of numbers), even a 0-D matrix (a single number), or a higher dimensional structure that is harder to visualize. The dimension of the tensor is called its rank.